server:
  port: 8781
spring:
  profiles:
    active: comp
  application:
    name: order-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/,http://arthas:123456@peer1:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
product-service:
  ribbon:
    #负载均衡策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    #最大重试次数
    MaxAutoRetries: 2
    #最大重试服务器次数(比如设为1,集群总共3个节点,尝了第一个节点没连上后会尝试第二个节点,不成功就不会再尝第三个节点了)
    MaxAutoRetriesNextServer: 2
    #是否所有操作都可以重试.通常为false,post请求不会重试
    OkToRetryOnAllOperations: false
    #服务列表刷新间隔
    ServerListRefreshInterval: 2000
    #连接超时设置
    ConnectTimeout: 3000
    #读取返回超时设置
    ReadTimeout: 3000
---
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: wjy199889
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles: comp