server:
  port: 8771
spring:
  profiles:
    active: comp
eureka:
  client:
    serviceUrl:
      defaultZone: http://arthas:123456@localhost:8761/eureka/
  instance:
    appname: product-service
management:
  endpoints:
    web:
      exposure:
        include: '*'
---
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: wjy199889
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles: comp