server:
  port: 8761
  environment: prod
  datacenter: home
spring:
  security:
    user:
      name: arthas
      password: 123456
eureka:
  instance:
    appname: server
    hostname: peer1
    prefer-ip-address: true
    instance-id: ${eureka.instance.appname}:${server.port}
  client:
    #    registerWithEureka: false
    #    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/
#eureka:
#  server:
#    enable-self-preservation: true
#    renewal-percent-threshold: 0.85
#    renewal-threshold-update-interval-ms: 6000
#    eviction-interval-timer-in-ms: 5000
#    delta-retention-timer-interval-in-ms: 30000