server:
  port: 8761
  environment: prod
  datacenter: home
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  security:
    user:
      name: arthas
      password: 123456
#eureka:
#  server:
#    enable-self-preservation: true
#    renewal-percent-threshold: 0.85
#    renewal-threshold-update-interval-ms: 6000
#    eviction-interval-timer-in-ms: 5000
#    delta-retention-timer-interval-in-ms: 30000