server:
  port: 8763
eureka:
  instance:
    hostname: peer3
    appname: server3
    prefer-ip-address: true
    instance-id: ${eureka.instance.appname}:${server.port}
  client:
    service-url:
      default-zone: http://localhost:8762/eureka/