server:
  port: 8762
spring:
  profiles:
    active: peer2
---
eureka:
  instance:
    hostname: peer2
    appname: server
    prefer-ip-address: true
    instance-id: ${eureka.instance.appname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://peer3:8763/eureka/,http://arthas:123456@peer1:8761/eureka/
spring:
  profiles: peer2