server:
  port: 8762
eureka:
  instance:
    hostname: peer2
    appname: server2
    prefer-ip-address: true
    instance-id: ${eureka.instance.appname}:${server.port}
  client:
    service-url:
      default-zone: http://localhost:8763/eureka/